#ifndef AURefreshViewDelegate_Protocol_h
#define AURefreshViewDelegate_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AURefreshView;

@protocol AURefreshViewDelegate <NSObject>

@optional
- (void)auRefreshView:(AURefreshView *)arg1 updateContentInset:(struct UIEdgeInsets)arg2;
- (void)auRefreshView:(AURefreshView *)arg1 updateContentInset:(struct UIEdgeInsets)arg2 status:(unsigned long long)arg3;
- (void)auRefreshView:(AURefreshView *)arg1 updateContentOffset:(struct CGPoint)arg2;
- (void)auRefreshViewDidDidFinishAnimation:(AURefreshView *)arg1;
- (void)auRefreshViewDidFinishAnimation:(AURefreshView *)arg1;
- (void)auRefreshViewDidTriggerloading:(AURefreshView *)arg1;
- (void)auRefreshViewWillFinishAnimation:(AURefreshView *)arg1;
@end

#endif