#ifndef LIVActionProcessUnit_Protocol_h
#define LIVActionProcessUnit_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol LIVActionProcessUnit <NSObject>
- (_Bool)processActionWithData:(NSDictionary *)arg1 completion:(void (^)(NSDictionary *))arg2;
- (_Bool)registerAction:(void (^)(NSDictionary *, id <LIVActionProcessUnit>, void (^)(NSDictionary *)))arg1 forName:(NSString *)arg2 object:(id)arg3;
- (void)unregisterActionForName:(NSString *)arg1 object:(id)arg2;
@end

#endif