#ifndef RVAOptionsProtocol_Protocol_h
#define RVAOptionsProtocol_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSObject, NSString, RVAViewControllerProxy;
@protocol RVAOptionsProtocol;

@protocol RVAOptionsProtocol <NSObject>
@property(copy, nonatomic) NSString *backBehavior;
@property(nonatomic) long long backgroundColor;
@property(copy, nonatomic) NSString *bizScenario;
@property(nonatomic) _Bool canPullDown;
@property(copy, nonatomic) NSString *closeButtonText;
@property(retain, nonatomic) NSObject *customParams;
@property(copy, nonatomic) NSString *defaultSubtitle;
@property(copy, nonatomic) NSString *defaultTitle;
@property(nonatomic) _Bool enableJSC;
@property(nonatomic) _Bool fullscreen;
@property(nonatomic) _Bool gestureBack;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithOptions:(id <RVAOptionsProtocol>)arg1 overrides:(NSDictionary *)arg2;
@property(copy, nonatomic) NSString *landscape;
@property(copy, nonatomic) NSString *nbl_id;
@property(nonatomic) _Bool pullRefresh;
@property(copy, nonatomic) NSString *pushingURLString;
@property(nonatomic) _Bool readTitle;
@property(nonatomic) _Bool showDomain;
@property(nonatomic) _Bool showLoading;
@property(nonatomic) _Bool showOptionMenu;
@property(nonatomic) _Bool showProgress;
@property(nonatomic) _Bool showStatusBar;
@property(nonatomic) _Bool showTitleBar;
@property(nonatomic) _Bool showTitleLoading;
@property(nonatomic) _Bool showToolBar;
@property(copy, nonatomic) NSString *titleImage;
@property(copy, nonatomic) NSString *toolbarMenu;
@property(nonatomic) _Bool transparent;
@property(copy, nonatomic) NSString *url;
@property(nonatomic) __weak RVAViewControllerProxy *viewControllerProxy;
@end

#endif