#ifndef RVATabBarProtocol_Protocol_h
#define RVATabBarProtocol_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, UITabBar, UIViewController;

@protocol RVATabBarProtocol <NSObject>
+ (long long)indexWithUrl:(NSString *)arg1 tabConfigDict:(NSDictionary *)arg2 isTinyApp:(_Bool)arg3;
- (void)adjustTabBarContentEdgeInsetsBottom:(double)arg1;
@property(retain, nonatomic) NSDictionary *cachedChildViewControllers;
@property(nonatomic) __weak UIViewController *cachedParentViewController;
@property(readonly, nonatomic) unsigned long long childTabCount;
- (UIViewController *)childTabViewController;
- (void)createTabBarWithConfig:(NSDictionary *)arg1 selectedIndex:(unsigned long long)arg2;
@property(readonly, nonatomic) NSMutableArray *delayTabBarTasks;
- (void)destroyPlaceholderTabBarIfExist;
@property(nonatomic) _Bool hasAlphaBackgroundColor;
@property(readonly, nonatomic) _Bool hasChildTab;
- (void)hideTabBarWithAnimationType:(NSString *)arg1 animated:(_Bool)arg2;
- (long long)index4TabBarItemTag:(NSString *)arg1;
@property(nonatomic) _Bool isChildTab;
@property(readonly, nonatomic) _Bool isNotVisibleWhenMultiTab;
- (_Bool)isSwitching;
- (NSString *)p_tag4TabBarIndex:(unsigned long long)arg1;
- (void)placeholdTabBarWithItemCount:(unsigned long long)arg1;
@property(retain, nonatomic) UITabBar *placeholderTabBar;
@property(retain, nonatomic) NSString *selectedTag;
@property(readonly, nonatomic) UIViewController *selectedViewController;
- (void)setIcon:(NSString *)arg1 scale:(float)arg2 atTag:(NSString *)arg3 forSelected:(_Bool)arg4;
@property(nonatomic) _Bool stopConstructAppearance;
- (void)setTabBarBadge:(NSString *)arg1 tag:(NSString *)arg2;
- (void)setTabBarGapHeight:(double)arg1;
- (void)setTabBarHeight:(double)arg1;
- (_Bool)shouldDisableTabBarWhenShare:(NSString *)arg1;
- (void)showTabBarWithAnimationType:(NSString *)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UITabBar *tabBar;
- (void)tabBarColorModeWillChange:(unsigned long long)arg1;
- (void)tabBarFontSizeWillChange:(long long)arg1;
- (double)textFontScale;
- (double)textFontSize;
- (void)updateChildTabNavigationItems;

@optional
- (void)rvptab_childViewWillDestroy;
- (void)setSelectedTag:(NSString *)arg1 sourceViewController:(UIViewController *)arg2;
@end

#endif