#ifndef RVKContentViewDelegate_Protocol_h
#define RVKContentViewDelegate_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, RVKContentView;

@protocol RVKContentViewDelegate <NSObject>

@optional
- (void)callHandler:(NSString *)arg1 data:(id)arg2 responseCallback:(void (^)(id))arg3;
- (_Bool)contentView:(RVKContentView *)arg1 resizeFrame:(struct CGRect)arg2;
@end

#endif