#ifndef RVKPluginProtocol_Protocol_h
#define RVKPluginProtocol_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, RVKEvent, RVKKernel;

@protocol RVKPluginProtocol <NSObject>
- (void)handleEvent:(RVKEvent *)arg1;
@property(readonly, copy, nonatomic) NSString *name;

@optional
- (void)associateWeakTarget:(RVKKernel *)arg1;
- (NSString *)group;
- (int)priority;
@end

#endif