#ifndef RVKSceneSubClass_Protocol_h
#define RVKSceneSubClass_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RVKSceneParam, RVKView;

@protocol RVKSceneSubClass <NSObject>
- (void)customActionAfterNodeCreation:(RVKView *)arg1;
- (void)customCreateVC:(RVKSceneParam *)arg1;
- (void)setSceneParam:(RVKSceneParam *)arg1;
@end

#endif