#ifndef AURefreshView_h
#define AURefreshView_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AUAntRefreshLottieView, UIScrollView;
@protocol AURefreshViewDelegate;

@interface AURefreshView : UIView
{
    double _lastOffset;
    unsigned long long _viewType;
    struct CGPoint _originOffset;
    struct CGPoint _latestOffset;
    id _completion;
    _Bool _immediatelyColse;
    _Bool _shouldPlayTransition;
    _Bool _isHapticFeedBack;
    _Bool _audioPlaying;
    _Bool _scrollToTop;
    _Bool _animationComplete;
    _Bool _isVisible;
    unsigned long long _state;
    id <AURefreshViewDelegate> _delegate;
    AUAntRefreshLottieView *_antLottieView;
    UIScrollView *_scrollView;
    id _refreshBlock;
    struct UIEdgeInsets _originEdgeInset;
}

+ (_Bool)AURefreshView_AnimationDuration_Rollback;
@property(nonatomic) _Bool animationComplete; // @synthesize animationComplete=_animationComplete;
- (void)animationFinished;
@property(retain, nonatomic) AUAntRefreshLottieView *antLottieView; // @synthesize antLottieView=_antLottieView;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)auRefreshScrollViewDidEndDecelerating:(id)arg1;
- (void)auRefreshScrollViewDidEndDragging:(id)arg1;
- (void)auRefreshScrollViewDidFinishedLoading:(id)arg1;
- (void)auRefreshScrollViewDidFinishedLoading:(id)arg1 completion:(id)arg2;
- (void)auRefreshScrollViewDidFinishedLoading:(id)arg1 immediatelyColse:(_Bool)arg2 completion:(id)arg3;
- (void)auRefreshScrollViewDidScroll:(id)arg1;
- (void)auRefreshScrollViewWillBeginDragging:(id)arg1;
@property(nonatomic) _Bool audioPlaying; // @synthesize audioPlaying=_audioPlaying;
- (void)autoPullRefreshScrollView:(id)arg1;
- (void)autoPullRefreshScrollView:(id)arg1 animated:(_Bool)arg2;
- (void)beginDraggingStateUpdate:(id)arg1;
- (void)changeToNewType:(unsigned long long)arg1;
- (void)changeType:(unsigned long long)arg1;
- (void)changeType:(unsigned long long)arg1 completion:(id)arg2;
- (void)checkResetContentOffsetY;
- (long long)currerntTitleDisplay;
- (void)dealloc;
@property(nonatomic) __weak id <AURefreshViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithSuperView:(id)arg1 type:(unsigned long long)arg2 bizType:(id)arg3;
@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;
@property(nonatomic) struct UIEdgeInsets originEdgeInset; // @synthesize originEdgeInset=_originEdgeInset;
- (void)pauseAnimation;
- (void)performResetScrollView;
@property(copy, nonatomic) id refreshBlock; // @synthesize refreshBlock=_refreshBlock;
- (void)resetAniamtionFrame:(double)arg1;
- (void)resetScrollView;
- (void)resetScrollViewPosition;
- (void)resumeAnimation;
- (void)scrollHandler;
@property(nonatomic) _Bool scrollToTop; // @synthesize scrollToTop=_scrollToTop;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setupCustomView:(id)arg1;
- (void)setupForeColor:(id)arg1;
- (void)setupLabelForeColor:(id)arg1;
- (void)setupLabelText:(id)arg1;
- (void)setupTitleImage:(id)arg1;
- (void)startCloseAnimation;
- (void)startLoopAnimation;
@property(readonly, nonatomic) unsigned long long state; // @synthesize state=_state;
- (void)stopAnimating;
- (void)updateScrollViewInset:(struct UIEdgeInsets)arg1 status:(unsigned long long)arg2;
- (void)updateScrollViewOffset:(struct CGPoint)arg1 status:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long viewType; // @synthesize viewType=_viewType;

@end

#endif