#ifndef AUSearchBar_h
#define AUSearchBar_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class AUSearchBarLayoutConfig, NSDictionary, NSString, UIButton, UIColor, UIImageView, UITextField;
@protocol AUSearchBarDelegate;

@interface AUSearchBar : UIView <UITextFieldDelegate>
{
    _Bool _isSupportHanziMode;
    _Bool _shouldShowVoiceButton;
    _Bool _isActive;
    NSString *_text;
    unsigned long long _style;
    id <AUSearchBarDelegate> _delegate;
    long long _inputMaxLength;
    NSString *_placeHolder;
    UIColor *_placeHolderColor;
    UIView *_customRightView;
    AUSearchBarLayoutConfig *_layoutConfig;
    id _customStyleBlock;
    UIImageView *_searchTextFieldBackgroundView;
    UIView *_bottomSeparatorView;
    NSString *_oldText;
    double _cancelButtonWidth;
    UIButton *_cancelButton;
    UIButton *_backButton;
    UITextField *_searchTextField;
    UIImageView *_searchIconView;
    UIButton *_voiceIconButton;
    UIView *_backgroundView;
    NSDictionary *_customUIDic;
}

- (void)autoSetSubViewFrames;
- (void)back:(id)arg1;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
- (void)cancel:(id)arg1;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) double cancelButtonWidth; // @synthesize cancelButtonWidth=_cancelButtonWidth;
- (void)checkInputTextMaxLengthWithTextField:(id)arg1;
- (void)commonInit;
@property(retain, nonatomic) UIView *customRightView; // @synthesize customRightView=_customRightView;
@property(copy, nonatomic) id customStyleBlock; // @synthesize customStyleBlock=_customStyleBlock;
@property(retain, nonatomic) NSDictionary *customUIDic; // @synthesize customUIDic=_customUIDic;
@property(nonatomic) __weak id <AUSearchBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickSearchBar:(id)arg1;
- (void)hideBottomSeparator:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withStyle:(unsigned long long)arg2;
- (id)initWithStyle:(unsigned long long)arg1;
@property(nonatomic) long long inputMaxLength; // @synthesize inputMaxLength=_inputMaxLength;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property(nonatomic) _Bool isSupportHanziMode; // @synthesize isSupportHanziMode=_isSupportHanziMode;
@property(retain, nonatomic) AUSearchBarLayoutConfig *layoutConfig; // @synthesize layoutConfig=_layoutConfig;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *oldText; // @synthesize oldText=_oldText;
- (void)openVoiceAssister:(id)arg1;
@property(retain, nonatomic) NSString *placeHolder; // @synthesize placeHolder=_placeHolder;
@property(retain, nonatomic) UIColor *placeHolderColor; // @synthesize placeHolderColor=_placeHolderColor;
@property(retain, nonatomic) UIImageView *searchIconView; // @synthesize searchIconView=_searchIconView;
@property(retain, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(retain, nonatomic) UIImageView *searchTextFieldBackgroundView; // @synthesize searchTextFieldBackgroundView=_searchTextFieldBackgroundView;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool shouldShowVoiceButton; // @synthesize shouldShowVoiceButton=_shouldShowVoiceButton;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void)setTextFieldTextandEditingChanged:(id)arg1;
@property(retain, nonatomic) UIButton *voiceIconButton; // @synthesize voiceIconButton=_voiceIconButton;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldTextDidChange:(id)arg1;
- (void)updateSearchBarAppearance;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif