#ifndef DTBaseViewController_h
#define DTBaseViewController_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "DTNavigationBarAppearanceProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class APBaseLoadingView, DTMicroApplication, NSMutableArray, NSString, UIActivityIndicatorView, UIBarButtonItem, UINavigationController, UIView;

@interface DTBaseViewController : UIViewController <UIGestureRecognizerDelegate, DTNavigationBarAppearanceProtocol>
{
    NSString *_pageId;
    _Bool _is3DTouchLaunch;
    _Bool _isAutoSetNavBarStyle;
    _Bool _canDismissViewController;
    _Bool _needShowTitleLoading;
    unsigned long long _viewAppearState;
    UIBarButtonItem *_baseBackBarButtonItem;
    id _ueoPageCompletionBlock;
    NSMutableArray *_asyncCallers;
    NSString *_backButtonTitle;
    UIActivityIndicatorView *_titleLoading;
    UIView *_navItemView;
    APBaseLoadingView *_baseLoadingView;
    UINavigationController *_privateDTNavigationController;
    UINavigationController *_weakNavigationController;
}

+ (void)dismissAlertViews;
- (void)_languageSettingDidChange:(id)arg1;
- (void)_setDisplayStatusBarStyle:(_Bool)arg1;
- (_Bool)_statusBarDarkModeEnable;
- (_Bool)accessibilityPerformEscape;
- (void)addLoadingView:(id)arg1;
@property(readonly, nonatomic) DTMicroApplication *application;
@property(retain, nonatomic) NSMutableArray *asyncCallers; // @synthesize asyncCallers=_asyncCallers;
- (_Bool)aut_isCustomStatusBarStyleIsEnable;
- (_Bool)autoDismissAPActionSheets;
- (_Bool)autohideNavigationBar;
- (void)back;
- (id)backButtonDefaultTitle;
@property(retain, nonatomic) NSString *backButtonTitle; // @synthesize backButtonTitle=_backButtonTitle;
@property(nonatomic) __weak UIBarButtonItem *baseBackBarButtonItem; // @synthesize baseBackBarButtonItem=_baseBackBarButtonItem;
@property(retain, nonatomic) APBaseLoadingView *baseLoadingView; // @synthesize baseLoadingView=_baseLoadingView;
- (id)callAsyncBlock:(id)arg1 completion:(id)arg2;
- (id)callNoMainThreadAsyncBlock:(id)arg1 completion:(id)arg2;
- (void)callbackViewWillDestroy:(id)arg1;
@property(nonatomic) _Bool canDismissViewController; // @synthesize canDismissViewController=_canDismissViewController;
- (_Bool)checkNavigationBarBackStyle;
- (void)checkPopGesture;
- (void)createBackButton;
- (void)createCustomNavigationItemView;
- (void)createTitleLoading;
- (id)customNavigationBar;
- (id)customNavigationBarBackButtonImage;
- (id)customNavigationBarBackButtonTitleColor;
- (id)customNavigationBarLoadingViewColors;
- (id)customNavigationBarTitleColor;
- (long long)customStatusBarStytle;
- (void)dealloc;
- (void)dismissAPActionSheets;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)displayBackButtonTitle;
- (void)displayNavBarStyle:(_Bool)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)getTitle;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) _Bool is3DTouchLaunch; // @synthesize is3DTouchLaunch=_is3DTouchLaunch;
@property(nonatomic) _Bool isAutoSetNavBarStyle; // @synthesize isAutoSetNavBarStyle=_isAutoSetNavBarStyle;
- (void)languageSettingDidChange:(id)arg1;
@property(retain, nonatomic) UIView *navItemView; // @synthesize navItemView=_navItemView;
@property(nonatomic) _Bool needShowTitleLoading; // @synthesize needShowTitleLoading=_needShowTitleLoading;
- (id)opaqueNavigationBarColor;
- (id)pageID;
- (void)presentModalViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;
@property(nonatomic) __weak UINavigationController *privateDTNavigationController; // @synthesize privateDTNavigationController=_privateDTNavigationController;
- (void)resetNavigationBarStyle:(_Bool)arg1;
- (void)setNavigationBarStyle;
@property(retain, nonatomic) UIActivityIndicatorView *titleLoading; // @synthesize titleLoading=_titleLoading;
@property(copy, nonatomic) id ueoPageCompletionBlock; // @synthesize ueoPageCompletionBlock=_ueoPageCompletionBlock;
@property(nonatomic) unsigned long long viewAppearState; // @synthesize viewAppearState=_viewAppearState;
@property(nonatomic) __weak UINavigationController *weakNavigationController; // @synthesize weakNavigationController=_weakNavigationController;
- (_Bool)shouldAutorotate;
- (_Bool)shouldRotateToPortraitWhenDisappear;
- (void)startLoading;
- (void)startTitleLoading;
- (void)stopAllAsyncBlock;
- (void)stopLoading;
- (void)stopTitleLoading;
- (unsigned long long)supportedInterfaceOrientations;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDestroy;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif