#ifndef H5Alert_h
#define H5Alert_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AUDialogDelegate-Protocol.h"

@class AUInputDialog, AUNoticeDialog, NSString, UIViewController;

@interface H5Alert : NSObject <AUDialogDelegate>
{
    id _alertCallback;
    AUNoticeDialog *_noticeDialog;
    AUInputDialog *_inputDialog;
    UIViewController *_vc;
    id _callback;
    id _confirmCallback;
    id _promptCallBack;
}

@property(copy, nonatomic) id alertCallback; // @synthesize alertCallback=_alertCallback;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)alertWithParams:(id)arg1 callback:(id)arg2;
@property(copy, nonatomic) id callback; // @synthesize callback=_callback;
- (void)clearRunScriptBlock;
@property(copy, nonatomic) id confirmCallback; // @synthesize confirmCallback=_confirmCallback;
- (id)confirmWithParams:(id)arg1 callback:(id)arg2;
- (void)dealloc;
- (void)dialogView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dialogView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
@property(nonatomic) __weak AUInputDialog *inputDialog; // @synthesize inputDialog=_inputDialog;
@property(retain, nonatomic) AUNoticeDialog *noticeDialog; // @synthesize noticeDialog=_noticeDialog;
@property(copy, nonatomic) id promptCallBack; // @synthesize promptCallBack=_promptCallBack;
- (id)promptWithParams:(id)arg1 callback:(id)arg2;
@property(nonatomic) __weak UIViewController *vc; // @synthesize vc=_vc;
- (_Bool)shouleCloseAlertFromContainerCheck;
- (id)showAlertWithParams:(id)arg1 callback:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif