#ifndef H5PullRefreshInterface_h
#define H5PullRefreshInterface_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AURefreshViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class AURefreshView, H5StickyBouncer, H5WebViewController, NSNumber, NSString, UIScrollView;

@interface H5PullRefreshInterface : NSObject <AURefreshViewDelegate, UIScrollViewDelegate>
{
    _Bool _pullRefreshing;
    _Bool _needObserveScroll;
    long long _cusPullRefreshRunId;
    AURefreshView *_refreshHeaderView;
    double _webviewOriginY;
    H5WebViewController *_vc;
    H5StickyBouncer *_stickyBouncer;
    NSNumber *_startDragTime;
    NSNumber *_startDragPointY;
}

- (void)auRefreshViewDidFinishAnimation:(id)arg1;
- (void)auRefreshViewDidTriggerloading:(id)arg1;
- (void)changeRefreshHeaderLabelForeColor:(id)arg1;
- (void)changeRefreshHeaderType:(unsigned long long)arg1 completion:(id)arg2;
- (void)createRefreshHeaderView;
- (void)createRefreshHeaderView:(_Bool)arg1;
- (void)cusPullRefreshEnd;
@property(nonatomic) long long cusPullRefreshRunId; // @synthesize cusPullRefreshRunId=_cusPullRefreshRunId;
- (void)cusPullRefreshStart;
- (double)getYFromRGBColor:(id)arg1;
- (id)h5WebView;
- (void)hideRefreshHeaderView;
@property(nonatomic) _Bool needObserveScroll; // @synthesize needObserveScroll=_needObserveScroll;
- (id)options;
@property(nonatomic) _Bool pullRefreshing; // @synthesize pullRefreshing=_pullRefreshing;
@property(retain, nonatomic) AURefreshView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
- (void)restorePullToRefresh;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) NSNumber *startDragPointY; // @synthesize startDragPointY=_startDragPointY;
@property(retain, nonatomic) NSNumber *startDragTime; // @synthesize startDragTime=_startDragTime;
@property(nonatomic) __weak H5StickyBouncer *stickyBouncer; // @synthesize stickyBouncer=_stickyBouncer;
@property(nonatomic) __weak H5WebViewController *vc; // @synthesize vc=_vc;
@property(nonatomic) double webviewOriginY; // @synthesize webviewOriginY=_webviewOriginY;
- (void)updateObserveScrollViewStatus:(_Bool)arg1;
- (void)updateScrollViewDelegate:(id)arg1;
- (void)updateStickyBouncerForceRecreate:(_Bool)arg1 options:(id)arg2;
- (id)webView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif