#ifndef LIVActionProcessUnitActionRegistry_h
#define LIVActionProcessUnitActionRegistry_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface LIVActionProcessUnitActionRegistry : NSObject
{
    NSMutableArray *_actions;
}

@property(retain, nonatomic) NSMutableArray *actions; // @synthesize actions=_actions;
- (id)actionsForName:(id)arg1;
- (_Bool)processActionWithData:(id)arg1 forUnit:(id)arg2 completion:(id)arg3;
- (_Bool)registerAction:(id)arg1 forName:(id)arg2 object:(id)arg3;
- (void)unregisterActionForName:(id)arg1 object:(id)arg2;

@end

#endif