#ifndef RVKScene_h
#define RVKScene_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKKernel.h"

#import "AntTranslatePageStatusDelegate-Protocol.h"
#import "RVKSceneNode-Protocol.h"
#import "RVKSceneSubClass-Protocol.h"
#import "RVKViewControllerLifeDelegate-Protocol.h"

@class NBAdvancedWhiteScreenTask, NSString, NebulaSceneRuntime, RVKSceneParam, UIViewController;
@protocol RVKViewControllerProtocol, RVKViewNode;

@interface RVKScene : RVKKernel <AntTranslatePageStatusDelegate, RVKSceneNode, RVKSceneSubClass, RVKViewControllerLifeDelegate>
{
    _Bool _createAsPreRender;
    _Bool _didUseAsPreRender;
    _Bool _hashChangeDidTrigger;
    _Bool _usePreRender;
    id <RVKViewNode> _rvkView;
    RVKSceneParam *_sceneParam;
    UIViewController<RVKViewControllerProtocol> *_rvkViewController;
}

+ (id)sceneWithSceneParam:(id)arg1 parentObject:(id)arg2;
- (id)H5CustomPopMenu;
- (id)H5SettingPopMenu;
- (id)H5ShareParamsPopMenu;
- (void)_commonInit:(id)arg1 sceneParam:(id)arg2;
- (void)_onViewCotrollerCreate:(id)arg1 withSceneParams:(id)arg2;
- (void)antTranslateStatusDidChange:(id)arg1 event:(long long)arg2;
- (id)apPageId;
- (id)apViewId;
- (void)callHandler:(id)arg1 data:(id)arg2 callbackImmediatelyIfJSBridgeNotReady:(_Bool)arg3 responseCallback:(id)arg4;
- (void)callHandler:(id)arg1 data:(id)arg2 responseCallback:(id)arg3;
@property(copy, nonatomic) NSString *channelId;
- (id)codeSnippets4InsertAlipayJsBridgeFile;
@property(nonatomic) _Bool createAsPreRender; // @synthesize createAsPreRender=_createAsPreRender;
- (id)createParam;
- (id)currentNavbarH5Center;
- (id)currentScene;
- (id)currentSession;
- (id)currentTranslateScene;
- (void)customActionAfterNodeCreation:(id)arg1;
- (void)customCreateVC:(id)arg1;
- (id)customCreateView:(id)arg1;
- (void)dealloc;
@property(nonatomic) unsigned long long delayTimeCheckResult;
@property(nonatomic) _Bool didUseAsPreRender; // @synthesize didUseAsPreRender=_didUseAsPreRender;
- (void)doPreFrameworkUsed:(id)arg1;
- (id)dyJsUrls;
- (id)findNodeWithChannel:(id)arg1;
@property(nonatomic) _Bool hasCheckedWhiteScreen;
@property(nonatomic) _Bool hashChangeDidTrigger; // @synthesize hashChangeDidTrigger=_hashChangeDidTrigger;
- (id)independenceUserScripts;
- (id)initWithSceneParam:(id)arg1 parentObject:(id)arg2;
- (void)injctIndependenceJs;
- (void)injctJsRelyOnAlipayJsBridge;
- (id)insertT2PreloadScript:(id)arg1;
@property(nonatomic) _Bool isPageLoaded;
@property(nonatomic) _Bool isTranslationEnabled;
@property(nonatomic) _Bool isTranslationRequested;
@property(nonatomic) _Bool isTranslationScriptInjected;
- (id)psdView;
- (id)psdView;
- (id)relayOnAlipayJsBridgeUserScripts;
- (unsigned long long)rendererType;
@property(readonly, nonatomic) NebulaSceneRuntime *runtime; // @dynamic runtime;
@property(retain, nonatomic) id <RVKViewNode> rvkView; // @synthesize rvkView=_rvkView;
@property(retain, nonatomic) UIViewController<RVKViewControllerProtocol> *rvkViewController; // @synthesize rvkViewController=_rvkViewController;
@property(retain, nonatomic) RVKSceneParam *sceneParam; // @synthesize sceneParam=_sceneParam;
- (void)sendEventAndExit;
- (void)sendTanslateEvnet:(long long)arg1;
- (id)session;
- (void)setCurrentNavbarH5Center:(id)arg1;
- (void)setH5CustomPopMenu:(id)arg1;
- (void)setH5SettingPopMenu:(id)arg1;
- (void)setH5ShareParamsPopMenu:(id)arg1;
- (void)setPsdView:(id)arg1;
- (void)setPsdView:(id)arg1;
- (void)setUseNavbarH5Center:(_Bool)arg1;
@property(nonatomic) _Bool usePreRender; // @synthesize usePreRender=_usePreRender;
@property(nonatomic) unsigned long long whiteScreenCheckResult;
@property(retain, nonatomic) NBAdvancedWhiteScreenTask *whiteScreenTask;
@property(readonly, nonatomic) NSString *sourceTagForComponentMgrWhenSceneDestroy;
- (id)startupParamsJs;
- (id)translateEmbedWebviewScene;
- (_Bool)updateTranslateEvent;
- (void)updateWhiteScreenCheckResult:(unsigned long long)arg1;
- (_Bool)useNavbarH5Center;
- (id)viewController;
- (void)viewController:(id)arg1 loadView:(_Bool)arg2;
- (void)viewController:(id)arg1 viewDidAppear:(_Bool)arg2;
- (void)viewController:(id)arg1 viewDidDisappear:(_Bool)arg2;
- (void)viewController:(id)arg1 viewDidLayoutSubviews:(_Bool)arg2;
- (void)viewController:(id)arg1 viewDidLoad:(_Bool)arg2;
- (void)viewController:(id)arg1 viewDidUnLoad:(_Bool)arg2;
- (void)viewController:(id)arg1 viewWillAppear:(_Bool)arg2;
- (void)viewController:(id)arg1 viewWillDestroy:(_Bool)arg2;
- (void)viewController:(id)arg1 viewWillDisappear:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif