#ifndef RVKView_h
#define RVKView_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKKernel.h"

#import "RVKContentViewDelegate-Protocol.h"
#import "RVKViewNode-Protocol.h"

@class NSString, RNGPreloadInstance, RVKContentView, RVKPage, RVKProgressiveRenderHelper, RVKViewParam, WKNavigation;
@protocol RVKRenderMonitorProtocol;

@interface RVKView : RVKKernel <RVKContentViewDelegate, RVKViewNode>
{
    WKNavigation *_firstNavigation;
    _Bool _firstLoad;
    _Bool _canMonitor;
    RVKPage *_page;
    id <RVKRenderMonitorProtocol> _renderMonitor;
    RVKViewParam *_viewParam;
    RVKContentView *_contentView;
    RNGPreloadInstance *_preloadInstance;
    RVKProgressiveRenderHelper *_progressiveRenderHelper;
}

+ (id)defaultProcessPool;
+ (_Bool)removeURLSchemeSpecialLogic4AjaxAndFormSubmit;
+ (void)saveCookieForStorage:(id)arg1;
+ (void)saveCookieForStorage:(id)arg1;
+ (id)viewWithViewParam:(id)arg1 parentObject:(id)arg2;
- (void)_setupWebview:(id)arg1 viewParam:(id)arg2;
- (void)addHeartBeatScript;
- (void)addOpenRateScript;
- (void)addViewIdUserScript;
- (void)callHandler:(id)arg1 data:(id)arg2 responseCallback:(id)arg3;
@property(nonatomic) _Bool canMonitor; // @synthesize canMonitor=_canMonitor;
- (void)cancelInjctJS;
- (void)cancelInjectJS;
- (void)checkFirstLoad;
@property(retain, nonatomic) RVKContentView *contentView; // @synthesize contentView=_contentView;
- (id)createParam;
- (id)currentScene;
- (id)currentSession;
- (void)dealloc;
- (void)doAddMessageHandler:(id)arg1;
- (id)doInitWithViewParam:(id)arg1 parentObject:(id)arg2;
- (void)doInjctJS;
@property(nonatomic) _Bool firstLoad; // @synthesize firstLoad=_firstLoad;
- (void)fixTouchCallout4PageByPageStartParams:(id)arg1;
- (id)getconfigJsListWithScene:(id)arg1;
- (void)handleCookieData:(id)arg1 url:(id)arg2;
- (void)handleWKCookie;
- (void)handleWKCookieFrom:(id)arg1;
- (void)initMessageChannel;
- (void)initWithReuseInstance:(id)arg1 viewParam:(id)arg2 parentObject:(id)arg3;
- (id)initWithViewParam:(id)arg1 parentObject:(id)arg2;
- (void)injctJS;
- (_Bool)isSupportProgressiveRender:(id)arg1;
- (void)loadRequest;
@property(readonly, nonatomic) RVKPage *page; // @synthesize page=_page;
- (void)pluginsJs;
@property(retain, nonatomic) RNGPreloadInstance *preloadInstance; // @synthesize preloadInstance=_preloadInstance;
- (void)progressiveLoadIndexJs:(id)arg1;
@property(retain, nonatomic) RVKProgressiveRenderHelper *progressiveRenderHelper; // @synthesize progressiveRenderHelper=_progressiveRenderHelper;
- (void)progressiveShowError:(id)arg1;
- (void)removeAllMessageHandler;
- (void)removeMessageHandler:(id)arg1;
@property(retain, nonatomic) id <RVKRenderMonitorProtocol> renderMonitor; // @synthesize renderMonitor=_renderMonitor;
- (void)restoreContentView;
- (id)rvkConig;
- (void)setTextInteraction4iOS15:(_Bool)arg1;
@property(retain, nonatomic) RVKViewParam *viewParam; // @synthesize viewParam=_viewParam;
- (void)setWebViewInvalid;
- (void)setupMessageHandler;
- (void)setupUserScripts;
- (void)setupView;
- (void)startLoadRequest;
- (void)syncDeviceCookieWithStorage:(id)arg1;
- (void)syncMainProcessCookie;
- (void)syncSimulatorCookieWithStorage:(id)arg1;
- (id)t2PreloadScript;
- (void)updateCreateParam:(id)arg1;
- (_Bool)usePreRenderWebView;
- (id)view;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (int)wkCrashTimes;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif