#ifndef RVPTabBarManager_h
#define RVPTabBarManager_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CAAnimationDelegate-Protocol.h"
#import "RVATabBarProtocol-Protocol.h"
#import "UITabBarDelegate-Protocol.h"

@class NSArray, NSDictionary, NSLayoutConstraint, NSMutableArray, NSString, UINavigationItem, UITabBar, UIViewController;
@protocol RVKViewControllerProtocol, RVPVCTabBarProtocol;

@interface RVPTabBarManager : NSObject <UITabBarDelegate, CAAnimationDelegate, RVATabBarProtocol>
{
    UIViewController<RVKViewControllerProtocol> *_viewController;
    _Bool _associated;
    _Bool _isChildTab;
    _Bool _stopConstructAppearance;
    _Bool _hasAlphaBackgroundColor;
    _Bool _enableOlderVersion;
    _Bool _isSwitching;
    _Bool _isLargeIconSize;
    _Bool _enableFontSizeFitable;
    UITabBar *_placeholderTabBar;
    UITabBar *_tabBar;
    NSMutableArray *_delayTabBarTasks;
    UIViewController *_cachedParentViewController;
    NSDictionary *_cachedChildViewControllers;
    unsigned long long _currentColorMode;
    NSArray *_supportColorSchemes;
    NSDictionary *_colorSchemeData;
    long long _fontSizeLevel;
    UINavigationItem *_origNavigationItem;
    NSMutableArray *_arrItemData;
    NSLayoutConstraint *_cstTabBarBottom;
    NSLayoutConstraint *_cstPlaceholdTabBarBottom;
    NSLayoutConstraint *_cstTabBarHeight;
    NSString *_tagAtTabBarController;
    id _nxTabDelegate;
    id <RVPVCTabBarProtocol> _vcTabbarImp;
}

+ (long long)indexWithUrl:(id)arg1 tabConfigDict:(id)arg2 isTinyApp:(_Bool)arg3;
+ (id)vcTabbarProtocolImp;
- (void)addRNGTabBar:(id)arg1 height:(double)arg2;
- (void)adjustTabBarContentEdgeInsetsBottom:(double)arg1;
- (id)animation4HideTabBarWithType:(id)arg1;
- (id)animation4ShowTabBarWithType:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
@property(retain, nonatomic) NSMutableArray *arrItemData; // @synthesize arrItemData=_arrItemData;
- (void)associateToViewController:(id)arg1;
@property(nonatomic) _Bool associated; // @synthesize associated=_associated;
@property(retain, nonatomic) NSDictionary *cachedChildViewControllers; // @synthesize cachedChildViewControllers=_cachedChildViewControllers;
@property(nonatomic) __weak UIViewController *cachedParentViewController; // @synthesize cachedParentViewController=_cachedParentViewController;
@property(readonly, nonatomic) unsigned long long childTabCount;
- (id)childTabViewController;
@property(retain, nonatomic) NSDictionary *colorSchemeData; // @synthesize colorSchemeData=_colorSchemeData;
- (void)createTabBarWithConfig:(id)arg1 selectedIndex:(unsigned long long)arg2;
@property(nonatomic) __weak NSLayoutConstraint *cstPlaceholdTabBarBottom; // @synthesize cstPlaceholdTabBarBottom=_cstPlaceholdTabBarBottom;
@property(nonatomic) __weak NSLayoutConstraint *cstTabBarBottom; // @synthesize cstTabBarBottom=_cstTabBarBottom;
@property(nonatomic) __weak NSLayoutConstraint *cstTabBarHeight; // @synthesize cstTabBarHeight=_cstTabBarHeight;
@property(nonatomic) unsigned long long currentColorMode; // @synthesize currentColorMode=_currentColorMode;
- (id)currentColorModeString;
- (id)defaultSceneParamWithParams:(id)arg1 url:(id)arg2 vc:(id)arg3;
@property(retain, nonatomic) NSMutableArray *delayTabBarTasks; // @synthesize delayTabBarTasks=_delayTabBarTasks;
- (void)destroyPlaceholderTabBarIfExist;
@property(nonatomic) _Bool enableFontSizeFitable; // @synthesize enableFontSizeFitable=_enableFontSizeFitable;
@property(nonatomic) _Bool enableOlderVersion; // @synthesize enableOlderVersion=_enableOlderVersion;
@property(nonatomic) long long fontSizeLevel; // @synthesize fontSizeLevel=_fontSizeLevel;
- (double)fontSizeOfLevel:(long long)arg1;
- (double)fontSizeScaleOfLevel:(long long)arg1;
- (id)getBlankIconStrIfNeed:(id)arg1;
- (id)getColorForKey:(id)arg1 withConfig:(id)arg2;
- (id)getIconForKey:(id)arg1 fromData:(id)arg2 withIndex:(unsigned long long)arg3;
@property(nonatomic) _Bool hasAlphaBackgroundColor; // @synthesize hasAlphaBackgroundColor=_hasAlphaBackgroundColor;
@property(readonly, nonatomic) _Bool hasChildTab;
- (void)hideTabBarWithAnimationType:(id)arg1 animated:(_Bool)arg2;
- (long long)index4TabBarItemTag:(id)arg1;
- (id)initWithViewController:(id)arg1;
@property(nonatomic) _Bool isChildTab; // @synthesize isChildTab=_isChildTab;
@property(nonatomic) _Bool isLargeIconSize; // @synthesize isLargeIconSize=_isLargeIconSize;
@property(readonly, nonatomic) _Bool isNotVisibleWhenMultiTab;
@property(nonatomic) _Bool isSwitching; // @synthesize isSwitching=_isSwitching;
- (_Bool)needResetTabBarPosition;
- (void)notifyViewHierarchyChanged;
@property(nonatomic) __weak id nxTabDelegate; // @synthesize nxTabDelegate=_nxTabDelegate;
@property(retain, nonatomic) UINavigationItem *origNavigationItem; // @synthesize origNavigationItem=_origNavigationItem;
- (void)p_adjustInsetsOfViewController:(id)arg1;
- (id)p_appearanceWithTextColor:(id)arg1 selectedColor:(id)arg2 backgroundImage:(id)arg3;
- (id)p_backgroundImageFromBackgroundColor:(id)arg1;
- (void)p_createTabBarWithItems:(id)arg1 backgroundImage:(id)arg2 shadowImage:(id)arg3 selectedIndex:(unsigned long long)arg4 disableOnInit:(_Bool)arg5;
- (void)p_displayIcon:(id)arg1 defaultColor:(id)arg2 scale:(float)arg3 atBarItem:(id)arg4 forSelected:(_Bool)arg5;
- (double)p_getTabbarHeight;
- (void)p_placeholdTabBarImage:(id)arg1;
- (id)p_sceneParam:(id)arg1;
- (void)p_tabbarRefreshAppearance;
- (id)p_tag4TabBarIndex:(unsigned long long)arg1;
- (id)p_viewController4Tag:(id)arg1;
- (_Bool)parseFontSizeFitableFromConfig:(id)arg1;
- (void)placeholdTabBarWithItemCount:(unsigned long long)arg1;
@property(retain, nonatomic) UITabBar *placeholderTabBar; // @synthesize placeholderTabBar=_placeholderTabBar;
- (void)reLayoutTabBarBadge;
- (void)rvptab_childViewWillDestroy;
@property(retain, nonatomic) NSString *selectedTag;
@property(readonly, nonatomic) UIViewController *selectedViewController;
- (void)setIcon:(id)arg1 scale:(float)arg2 atTag:(id)arg3 forSelected:(_Bool)arg4;
- (void)setSelectedTag:(id)arg1 sourceViewController:(id)arg2;
@property(nonatomic) _Bool stopConstructAppearance; // @synthesize stopConstructAppearance=_stopConstructAppearance;
@property(retain, nonatomic) NSArray *supportColorSchemes; // @synthesize supportColorSchemes=_supportColorSchemes;
@property(retain, nonatomic) UITabBar *tabBar; // @synthesize tabBar=_tabBar;
- (void)setTabBarBadge:(id)arg1 tag:(id)arg2;
- (void)setTabBarGapHeight:(double)arg1;
- (void)setTabBarHeight:(double)arg1;
@property(retain, nonatomic) NSString *tagAtTabBarController; // @synthesize tagAtTabBarController=_tagAtTabBarController;
@property(nonatomic) __weak id <RVPVCTabBarProtocol> vcTabbarImp; // @synthesize vcTabbarImp=_vcTabbarImp;
- (_Bool)shouldDisableTabBarWhenShare:(id)arg1;
- (_Bool)shouldHideTabBarOnInit;
- (void)showTabBarWithAnimationType:(id)arg1 animated:(_Bool)arg2;
- (_Bool)supportCurrentColorMode;
- (void)tabBar:(id)arg1 beforeSelectIndex:(long long)arg2 item:(id)arg3;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)tabBarColorModeWillChange:(unsigned long long)arg1;
- (void)tabBarFontSizeWillChange:(long long)arg1;
- (id)tabbarHorizontalFormatStr;
- (double)textFontScale;
- (double)textFontSize;
- (void)updateChildTabNavigationItems;
- (void)viewSafeAreaInsetsDidChange;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif