#ifndef DTRpcAsyncCaller_h
#define DTRpcAsyncCaller_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSThread;

@interface DTRpcAsyncCaller : NSObject
{
    _Bool _cancelled;
    _Bool _finished;
    NSThread *_asyncThread;
}

+ (id)callAsyncBlock:(id)arg1 completion:(id)arg2;
+ (id)callNoMainThreadAsyncBlock:(id)arg1 completion:(id)arg2;
- (void)afterCompleteAction;
@property(nonatomic) __weak NSThread *asyncThread; // @synthesize asyncThread=_asyncThread;
- (void)beforeCompleteAction;
- (void)callerThreadCompletionBlock:(id)arg1;
- (void)callerThreadExecuteBlock:(id)arg1;
- (void)cancel;
- (void)clearThreadDictionary;
- (void)handleException:(id)arg1;
- (id)init;
@property(getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(getter=isFinished) _Bool finished; // @synthesize finished=_finished;
- (void)startAsyncBlock:(id)arg1 completion:(id)arg2;
- (void)startNoMainThreadAsyncBlock:(id)arg1 completion:(id)arg2;

@end

#endif