#ifndef RVKKernel_h
#define RVKKernel_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RVKEventTargetProtocol-Protocol.h"
#import "RVKExpandoProtocol-Protocol.h"
#import "RVKPluginProtocol-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, RVKExtensionNodeRegistry, RVKJsApiManager, RVKPluginManager;

@interface RVKKernel : NSObject <RVKPluginProtocol, RVKEventTargetProtocol, RVKExpandoProtocol>
{
    NSString *_uniqueId;
    RVKKernel *_parentEventTarget;
    NSMutableDictionary *_defaultNormalEventListenersDict;
    NSMutableDictionary *_expandoDict;
    NSMutableDictionary *_defaultCaptureEventListenersDict;
    NSMutableArray *_subObjectsArr;
    RVKJsApiManager *_jsApiManager;
    RVKPluginManager *_pluginManager;
    RVKExtensionNodeRegistry *_extensionManager;
    NSArray *_mExtensionList;
}

+ (double)physFootprint;
- (id)__eventListenersDictWithGroup:(id)arg1 useCapture:(_Bool)arg2;
- (id)__groupOfListener:(id)arg1;
- (void)_callEvent:(id)arg1 eventListenersDict:(id)arg2 key:(id)arg3;
- (void)addEventListener:(id)arg1 withListener:(id)arg2 useCapture:(_Bool)arg3;
- (void)addSubObject:(id)arg1;
- (unsigned long long)callEventListener:(id)arg1 event:(id)arg2;
- (id)currentScene;
- (id)currentSession;
- (void)dealloc;
@property(retain, nonatomic) NSMutableDictionary *defaultCaptureEventListenersDict; // @synthesize defaultCaptureEventListenersDict=_defaultCaptureEventListenersDict;
@property(retain, nonatomic) NSMutableDictionary *defaultNormalEventListenersDict; // @synthesize defaultNormalEventListenersDict=_defaultNormalEventListenersDict;
- (void)deleteExpando:(id)arg1;
- (_Bool)dispatchEvent:(id)arg1;
- (_Bool)dispatchEvent:(id)arg1 directToPlugins:(id)arg2;
- (_Bool)dispatchEvent:(id)arg1 exceptPlugins:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *expandoDict; // @synthesize expandoDict=_expandoDict;
- (id)extensionList;
@property(retain, nonatomic) RVKExtensionNodeRegistry *extensionManager; // @synthesize extensionManager=_extensionManager;
- (id)findNodeWithChannel:(id)arg1;
- (void)fireEvent:(id)arg1;
- (id)firstSubObject;
- (id)footer;
- (id)getData:(id)arg1;
- (id)getExpando:(id)arg1;
- (void)handleCaptureEvent:(id)arg1;
- (void)handleEvent:(id)arg1;
- (void)handleEvent:(id)arg1 evenListenersDict:(id)arg2;
- (void)handleNormalEvent:(id)arg1;
- (id)init;
- (unsigned long long)instancePlatform;
- (_Bool)isFirstSubObject;
@property(retain, nonatomic) RVKJsApiManager *jsApiManager; // @synthesize jsApiManager=_jsApiManager;
- (id)lastSubObject;
@property(retain, nonatomic) NSArray *mExtensionList; // @synthesize mExtensionList=_mExtensionList;
@property(readonly, copy, nonatomic) NSString *name;
- (unsigned long long)nodeType;
@property(nonatomic) __weak RVKKernel *parentEventTarget; // @synthesize parentEventTarget=_parentEventTarget;
- (id)parentKernelObject;
@property(retain, nonatomic) RVKPluginManager *pluginManager; // @synthesize pluginManager=_pluginManager;
- (int)priority;
- (void)removeEventListener:(id)arg1 withListener:(id)arg2 useCapture:(_Bool)arg3;
- (void)removeFirstSubObject;
- (void)removeFromSuperObject;
- (void)removeLastSubObject;
- (void)removeSubObject:(id)arg1;
- (id)scope;
- (void)sendEventAndExit;
- (void)setData:(id)arg1 data:(id)arg2;
- (void)setExpando:(id)arg1 withValue:(id)arg2;
- (void)setExtensions:(id)arg1;
@property(retain, nonatomic) NSMutableArray *subObjectsArr; // @synthesize subObjectsArr=_subObjectsArr;
@property(copy, nonatomic) NSString *uniqueId; // @synthesize uniqueId=_uniqueId;
- (id)subObjects;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif