#ifndef RVKSession_h
#define RVKSession_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKKernel.h"

#import "RVKSessionNode-Protocol.h"

@class NSString, RNGOverlayManager, RVKSessionParam, RVTAppRuntime, WKWebView;

@interface RVKSession : RVKKernel <RVKSessionNode>
{
    _Bool _isRender20;
    NSString *_sessionUUID;
    RVKSessionParam *_sessionParam;
    RNGOverlayManager *_overlayManager;
}

+ (void)initialize;
+ (id)sessionWithSessionParam:(id)arg1 expando:(id)arg2 parentObject:(id)arg3;
+ (id)sessionWithSessionParam:(id)arg1 parentObject:(id)arg2;
- (void)_commomInit:(id)arg1 parentObject:(id)arg2 sessionParam:(id)arg3;
- (void)afterAppModelInit;
- (id)appDataSourceManager;
- (id)appId;
- (id)appSesssionLaunchParams;
- (void)callHandler:(id)arg1 data:(id)arg2 responseCallback:(id)arg3;
- (void)cancelProcess;
@property(copy, nonatomic) id cancelTask;
- (void)clearPreRender;
- (id)createParam;
- (id)createScene:(id)arg1 preRenderParams:(id)arg2;
- (id)createScene:(id)arg1 preRenderParams:(id)arg2 kickOut:(id)arg3 isHit:(_Bool *)arg4;
- (id)currentRelatedMicroApplication;
- (id)currentScene;
- (id)currentSession;
@property(retain, nonatomic) WKWebView *daemonView;
- (void)dealloc;
@property(copy, nonatomic) id destroyTask;
- (void)dispatchSessionCreateEvent;
- (void)executeOrAddSceneReadytask:(id)arg1;
- (id)findNodeWithChannel:(id)arg1;
- (id)getEmbeddedWebViewParentSession;
- (id)getExtraGeneralFieldsForLog;
- (id)getPermissionManagerCompatibleWithXRiver;
- (id)getPluginApp:(id)arg1;
- (id)getWorkerCompatibleWithXRiver;
- (_Bool)hasTabBar;
- (id)initWithSessionParam:(id)arg1 expando:(id)arg2 parentObject:(id)arg3;
- (_Bool)isAppxNgSupportFeatureWithKey:(id)arg1;
- (_Bool)isCube;
- (_Bool)isDefaultRenderNative;
- (_Bool)isMainPkgCCDN;
@property(nonatomic) _Bool isMainSession;
- (_Bool)isOnBackgroundMode;
- (_Bool)isPageCube;
- (_Bool)isPaladin;
@property(nonatomic) _Bool isRender20; // @synthesize isRender20=_isRender20;
@property(nonatomic) _Bool isTranslationEnabled;
- (id)mainApp;
- (void)mergeStartOptions:(id)arg1 scene:(id)arg2;
- (void)modifyHasTabBar:(id)arg1;
- (id)mySubObjects;
@property(retain, nonatomic) RNGOverlayManager *overlayManager; // @synthesize overlayManager=_overlayManager;
@property(nonatomic) __weak RVKSession *pairSession;
- (id)preRenderQueue;
- (_Bool)preRenderScene:(id)arg1 preRenderParams:(id)arg2 kickOut:(id)arg3;
- (id)preRenderScenes;
@property(retain, nonatomic) id processResult;
@property(nonatomic) _Bool processing;
@property(copy, nonatomic) id readyTask;
- (void)registerPlugin:(id)arg1;
- (void)removePreRenderInRange:(struct _NSRange)arg1;
- (_Bool)routeAppXNG;
@property(readonly, nonatomic) RVTAppRuntime *runtime; // @dynamic runtime;
@property(copy, nonatomic) id saveTask;
- (id)scope;
- (id)session;
@property(retain, nonatomic) RVKSessionParam *sessionParam; // @synthesize sessionParam=_sessionParam;
@property(retain, nonatomic) NSString *sessionUUID; // @synthesize sessionUUID=_sessionUUID;
- (void)setPluginInfoExpandoesForApp:(id)arg1;
- (id)taskId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif