#ifndef RVKContentViewProtocol_Protocol_h
#define RVKContentViewProtocol_Protocol_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString, NSURL, NSURLRequest, RVKJSCallMonitor, UIScrollView, UIView, UIWindow, WKWebViewConfiguration;
@protocol RVAContentViewPageDelegate, RVKContentViewDelegate, RVKContentViewNavigationDelegate, RVKContentViewUIDelegate, RVKViewControllerProtocol, UIScrollViewDelegate;

@protocol RVKContentViewProtocol <NSObject>
@property(retain, nonatomic) RVKJSCallMonitor *evalJSMonitor;

@optional
@property(readonly, copy, nonatomic) NSURL *URL;
- (void)addScrollViewReadyTask:(void (^)(void))arg1;
@property(nonatomic) _Bool allowsInlineMediaPlayback;
@property(nonatomic) unsigned long long autoresizingMask;
@property(readonly, nonatomic) _Bool canGoBack;
@property(copy, nonatomic) NSString *channelId;
@property(readonly, copy, nonatomic) WKWebViewConfiguration *configuration;
- (void)contentViewDidClose;
- (void)contentViewDidLoad;
- (void)contentViewDidPause;
- (void)contentViewDidResume;
@property(nonatomic) unsigned long long dataDetectorTypes;
@property(nonatomic) __weak id delegate;
@property(nonatomic) _Bool detectsPhoneNumbers;
- (void)evaluateJavaScript:(NSString *)arg1 bizId:(NSString *)arg2 completionHandler:(void (^)(id, NSError *))arg3;
- (void)evaluateJavaScript:(NSString *)arg1 completionHandler:(void (^)(id, NSError *))arg2;
- (void)goBack;
- (void)goForward;
- (void)invalidAndReadyToDestroy;
@property(readonly, nonatomic) _Bool isLoading;
@property(readonly, nonatomic) _Bool isRvaPagePaused;
- (void)loadData:(NSData *)arg1 MIMEType:(NSString *)arg2 textEncodingName:(NSString *)arg3 baseURL:(NSURL *)arg4;
- (void)loadHTMLString:(NSString *)arg1 baseURL:(NSURL *)arg2;
- (void)loadRequest:(NSURLRequest *)arg1;
@property(copy, nonatomic) NSString *nbl_id;
@property(nonatomic) __weak id <RVAContentViewPageDelegate> pageDelegate;
- (id <RVKViewControllerProtocol>)psdViewController;
- (void)reload;
@property(readonly, nonatomic) NSURLRequest *request;
@property(nonatomic) __weak id <RVKContentViewDelegate> rvkContentViewDelegate;
@property(nonatomic) __weak id <RVKContentViewNavigationDelegate> rvkContentViewNavigationDelegate;
@property(nonatomic) __weak id <RVKContentViewUIDelegate> rvkContentViewUIDelegate;
@property(nonatomic) __weak id <RVKViewControllerProtocol> rvkViewController;
@property(nonatomic) _Bool scalesPageToFit;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)setScrollViewDelegate:(id <UIScrollViewDelegate>)arg1;
- (void)stopLoading;
@property(readonly, nonatomic) NSString *traceId;
@property(readonly, nonatomic) __weak UIView *view;
@property(readonly, nonatomic) UIWindow *window;
@end

#endif