#ifndef DFClientDelegate_h
#define DFClientDelegate_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "PKPushRegistryDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UNUserNotificationCenterDelegate-Protocol.h"

@class DFContext, NSMutableDictionary, NSString, UIWindow;

@interface DFClientDelegate : UIResponder <UNUserNotificationCenterDelegate, UIApplicationDelegate, PKPushRegistryDelegate>
{
    double _lastReportActive;
    _Bool _bootUpDone;
    _Bool _bootingUpFromRemoteNotification;
    _Bool _bootingUpFromLocalNotification;
    DFContext *_context;
    UIWindow *_window;
    NSMutableDictionary *_remotePushInfo;
    NSMutableDictionary *_bgDownloadBeginTime;
}

+ (id)sharedDelegate;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(id)arg3;
- (void)application:(id)arg1 didChangeStatusBarOrientation:(long long)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(id)arg3;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forLocalNotification:(id)arg3 completionHandler:(id)arg4;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(id)arg3;
- (void)application:(id)arg1 handleWatchKitExtensionRequest:(id)arg2 reply:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(id)arg3;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(id)arg2;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (_Bool)applicationDidFinishLaunchingForDefault:(id)arg1 options:(id)arg2;
- (_Bool)applicationDidFinishLaunchingForPrivacyAuth:(id)arg1 options:(id)arg2;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *bgDownloadBeginTime; // @synthesize bgDownloadBeginTime=_bgDownloadBeginTime;
- (_Bool)bootUp;
@property(nonatomic) _Bool bootUpDone; // @synthesize bootUpDone=_bootUpDone;
@property(nonatomic) _Bool bootingUpFromLocalNotification; // @synthesize bootingUpFromLocalNotification=_bootingUpFromLocalNotification;
@property(nonatomic) _Bool bootingUpFromRemoteNotification; // @synthesize bootingUpFromRemoteNotification=_bootingUpFromRemoteNotification;
- (_Bool)checkRepeatCallForPush:(id)arg1;
- (_Bool)containsCategory:(id)arg1;
@property(retain, nonatomic) DFContext *context; // @synthesize context=_context;
- (_Bool)doHandleOpenURL:(id)arg1 sourceApplication:(id)arg2 convertForRC:(_Bool)arg3 launching:(_Bool)arg4;
- (void)doVoIPRegistration;
- (void)handleCategoryAction:(id)arg1 launching:(_Bool)arg2;
- (void)handleNotificationAsLocal:(id)arg1 response:(id)arg2;
- (void)handleNotificationAsRemote:(id)arg1 launching:(_Bool)arg2;
- (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 launching:(_Bool)arg3;
- (void)handlePushNotificationWithUserInfo:(id)arg1;
- (_Bool)handleShortCutItem:(id)arg1;
- (void)handleUserActivityCallback:(id)arg1;
- (void)handleVoIPNotificationWithUserInfo:(id)arg1;
- (void)localNotificationRemoteLogging:(id)arg1;
- (void)logLaunchApplicationByScheme:(id)arg1 sourceApplication:(id)arg2 boot:(_Bool)arg3;
- (int)parseAppInTypeFromScheme:(id)arg1;
- (id)parseUrlQueryValueWithUrl:(id)arg1 key:(id)arg2;
- (void)pushRegistry:(id)arg1 didReceiveIncomingPushWithPayload:(id)arg2 forType:(id)arg3;
- (void)pushRegistry:(id)arg1 didUpdatePushCredentials:(id)arg2 forType:(id)arg3;
@property(retain, nonatomic) NSMutableDictionary *remotePushInfo; // @synthesize remotePushInfo=_remotePushInfo;
- (void)runInitFunction;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)setupUserNotificationCenter:(id)arg1;
- (_Bool)shouldDelayOpenUrl:(id)arg1;
- (void)startBootLoader;
- (void)trackBGDownload:(id)arg1 timeCost:(double)arg2;
- (double)usedMemory;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(id)arg3;
- (void)userNotificationCenter:(id)arg1 openSettingsForNotification:(id)arg2;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif