#ifndef RVKJsBridge_h
#define RVKJsBridge_h
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RVKJsBridgeInterface-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSString, RVKContentView, RVKPage, RVKTimelineLogger, RVKUnsupportMimeHandler, RVKVipBridgeHandler;
@protocol WKNavigationDelegate, WKUIDelegate;

@interface RVKJsBridge : NSObject <WKNavigationDelegate, WKUIDelegate, RVKJsBridgeInterface>
{
    _Bool _useRenderLayerIndependentMode;
    _Bool _firstMessage;
    _Bool _isNativeRender;
    _Bool _isBridgeReady;
    _Bool _isFailToLoad;
    _Bool _isTimeout;
    int _uniqueId;
    RVKVipBridgeHandler *_vipBridgeHandler;
    RVKTimelineLogger *_logger;
    RVKUnsupportMimeHandler *_unsupportMimeHandler;
    NSMutableArray *_bridgeReadyTasks;
    RVKPage *_page;
    NSMutableDictionary *_responseCallbacks;
    NSMutableArray *_startupMessageQueue;
    RVKContentView *_contentView;
    id <WKUIDelegate> _webViewUIDelegate;
    id <WKNavigationDelegate> _webViewNavigationDelegate;
    NSDate *_loadFinishedDate;
}

+ (id)bridge4Page:(id)arg1 pageParam:(id)arg2;
+ (_Bool)dispatchJsapiInFastMode:(id)arg1 targetNode:(id)arg2 responseCallback:(id)arg3;
+ (void)enableLogging;
+ (_Bool)shouldLogging;
- (id)_deserializeMessageJSON:(id)arg1;
- (void)_dispatchMessage:(id)arg1;
- (void)_doFlushH5ReportMessageQueue:(id)arg1 url:(id)arg2;
- (void)_doFlushMessageQueue:(id)arg1 url:(id)arg2;
- (void)_doFlushMonitorMessageQueue:(id)arg1 url:(id)arg2;
- (void)_flushH5ReportMessageQueue;
- (void)_flushMessageQueue;
- (void)_flushMessageQueueWithMessage:(id)arg1 url:(id)arg2;
- (void)_flushMessageQueueWithUrl:(id)arg1;
- (void)_flushMonitorMessageQueue;
- (void)_log:(id)arg1 json:(id)arg2;
- (void)_queueMessage:(id)arg1;
- (void)_queueMessageStashable:(id)arg1;
- (void)_sendData:(id)arg1 responseCallback:(id)arg2 handlerName:(id)arg3;
- (id)_serializeMessage:(id)arg1;
- (void)addDelayTask:(id)arg1;
- (void)addDelayedTaskAfterBridgeReady:(id)arg1;
@property(retain, nonatomic) NSMutableArray *bridgeReadyTasks; // @synthesize bridgeReadyTasks=_bridgeReadyTasks;
- (void)callHandler:(id)arg1;
- (void)callHandler:(id)arg1 data:(id)arg2;
- (void)callHandler:(id)arg1 data:(id)arg2 responseCallback:(id)arg3;
- (void)callJsApi:(id)arg1 url:(id)arg2 data:(id)arg3 callFrom:(unsigned long long)arg4 disableCheckPermission:(_Bool)arg5 responseCallback:(id)arg6;
- (void)callJsApi:(id)arg1 url:(id)arg2 data:(id)arg3 responseCallback:(id)arg4;
@property(nonatomic) __weak RVKContentView *contentView; // @synthesize contentView=_contentView;
- (id)createCallHandlerInvocationEvent:(id)arg1 data:(id)arg2 responseCallback:(id)arg3;
- (void)dealloc;
- (void)diagnoseLogIfHashChange:(id)arg1;
- (void)diagnoseLogIfHashChange:(id)arg1;
- (_Bool)dispatchJsapiInFastMode:(id)arg1 responseCallback:(id)arg2;
- (void)doLoadJSBridgeFileWithDyInjctJsCodeSnippets:(id)arg1;
- (void)doLog:(id)arg1 message:(id)arg2;
- (void)doLog:(id)arg1 title:(id)arg2 body:(id)arg3 uniqId:(id)arg4;
- (void)doLogOnceQueueHasMessage:(id)arg1 webviewUrl:(id)arg2;
- (void)doSendData:(id)arg1 responseCallback:(id)arg2 handlerName:(id)arg3;
@property(nonatomic) _Bool firstMessage; // @synthesize firstMessage=_firstMessage;
- (void)flushResponseCallbacks;
- (id)getPanelTitleWithType:(int)arg1 webView:(id)arg2;
- (id)ignoreDiagnoseEventList;
- (id)init;
- (id)initWithPage:(id)arg1 pageParams:(id)arg2;
@property(nonatomic) _Bool isBridgeReady; // @synthesize isBridgeReady=_isBridgeReady;
- (_Bool)isCurrentVCAnimationFinished;
- (_Bool)isCurrentVCVisible;
@property(nonatomic) _Bool isFailToLoad; // @synthesize isFailToLoad=_isFailToLoad;
@property(nonatomic) _Bool isNativeRender; // @synthesize isNativeRender=_isNativeRender;
@property(nonatomic) _Bool isTimeout; // @synthesize isTimeout=_isTimeout;
- (id)javaScriptPanelTitleWithWebView:(id)arg1;
- (void)loadFinished;
@property(retain, nonatomic) NSDate *loadFinishedDate; // @synthesize loadFinishedDate=_loadFinishedDate;
- (void)loadJS:(id)arg1;
- (void)loadJSBridgeFileWithDyInjctJsCodeSnippets:(id)arg1;
@property(retain, nonatomic) RVKTimelineLogger *logger; // @synthesize logger=_logger;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) __weak RVKPage *page; // @synthesize page=_page;
- (void)reset;
@property(retain, nonatomic) NSMutableDictionary *responseCallbacks; // @synthesize responseCallbacks=_responseCallbacks;
- (void)send:(id)arg1;
- (void)send:(id)arg1 responseCallback:(id)arg2;
@property(retain, nonatomic) NSMutableArray *startupMessageQueue; // @synthesize startupMessageQueue=_startupMessageQueue;
@property(nonatomic) int uniqueId; // @synthesize uniqueId=_uniqueId;
@property(retain, nonatomic) RVKUnsupportMimeHandler *unsupportMimeHandler; // @synthesize unsupportMimeHandler=_unsupportMimeHandler;
@property(nonatomic) _Bool useRenderLayerIndependentMode; // @synthesize useRenderLayerIndependentMode=_useRenderLayerIndependentMode;
@property(retain, nonatomic) RVKVipBridgeHandler *vipBridgeHandler; // @synthesize vipBridgeHandler=_vipBridgeHandler;
@property(nonatomic) __weak id <WKNavigationDelegate> webViewNavigationDelegate; // @synthesize webViewNavigationDelegate=_webViewNavigationDelegate;
@property(nonatomic) __weak id <WKUIDelegate> webViewUIDelegate; // @synthesize webViewUIDelegate=_webViewUIDelegate;
- (_Bool)shouldFixFlushMessageQueueSourceUrl;
- (_Bool)shouldForbidFlushMessageQueueFromNavigate;
- (_Bool)shouldHandleFlushMessageQueueEmptySourceUrl;
- (_Bool)shouldIgnoreDiagnoseEvent:(id)arg1;
- (_Bool)shouldIgnoreDiagnoseEvent:(id)arg1;
- (_Bool)shouldLogMessage2Webview;
- (_Bool)shouldLogMessage2Webview4RenderLayerIndependentMode;
- (id)transformResponseData:(id)arg1;
- (void)updateBridgeReadyStatus:(id)arg1;
- (_Bool)utils_beforeInvocation:(id)arg1 userInfo:(id)arg2 responseCallback:(id)arg3;
- (void)utils_callJsApi:(id)arg1 responseCallback:(id)arg2;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(id)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(id)arg3;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(id)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(id)arg4;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(id)arg4;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(id)arg5;
- (void)webViewDidClose:(id)arg1;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)wkLoadFinisd;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

#endif